/*
 * Copyright (C) 2009, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: epivers.h,v 1.1 2010/08/05 21:58:58 ywu Exp $
 *
*/

#ifndef _epivers_h_
#define _epivers_h_

#define	EPI_MAJOR_VERSION	5

#define	EPI_MINOR_VERSION	60

#define	EPI_RC_NUMBER		120

#define	EPI_INCREMENTAL_NUMBER	1

#define EPI_BUILD_NUMBER	2

#define	EPI_VERSION		5, 60, 120, 1

#define	EPI_VERSION_NUM		0x053c7801

#define EPI_VERSION_DEV		5.60.0

/* Driver Version String, ASCII, 32 chars max */
#ifdef DSLCPE
#define	EPI_VERSION_STR		DSLCPE_WLAN_VERSION
#else
#ifdef WLTEST
#define	EPI_VERSION_STR		"5.60.120.1  (WLTEST)"
#else
#define	EPI_VERSION_STR		"5.60.120.1 "
#endif
#endif

#endif /* _epivers_h_ */
