/*
 * Copyright (C) 2009, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: router_version.h,v 1.1 2010/08/05 21:58:59 ywu Exp $
 *
*/

#ifndef _version_h_
#define _version_h_

#define	ROUTER_MAJOR_VERSION		5

#define	ROUTER_MINOR_VERSION		70

#define	ROUTER_RC_NUMBER		48

#define	ROUTER_INCREMENTAL_NUMBER	1

#define	ROUTER_BUILD_NUMBER		0

#define	ROUTER_VERSION			5, 70, 48, 1

#define	ROUTER_VERSION_NUM		0x05463001

/* Version String, ASCII, 32 chars max */
#define	ROUTER_VERSION_STR		"5.70.48.1"

#endif /* _version_h_ */
